### ISSUE TITLE
syntax rule not working

### ISSUE THREAD

**Issue by totalamd** [foo123/editor-grammar#5]
I wanna change syntax rule to allow _trailing comma_ in JSON arrays, so I change
`"literal_array" : "'[' (literal_value (',' literal_value)*)? ']'"`
to
`"literal_array" : "'[' (literal_value (',' literal_value)* (',')? )? ']'"`
But seems it not works. What I do wrong?
Error:

> error: Token "atom": true|false|null Expected | Token "string" Expected | Token "number" Expected | Token "[" Expected | Token "{" Expected

**Comment by foo123** [comment]
What you 've done is not going to work as you think since the `(',' literal_value)*` rule part is first and tries to match a comma (even a trailing comma) but then tries to match a `literal_value`. You can make the `literal_value` optional like this:

```text
"literal_array" : "'[' (literal_value (',' literal_value?)*)? ']'"
```

But this will allow many trailing commas. Else you can take a try using `lookahead` tokens and refine the rule to match only a single trailing comma, assuming no `literal_value` is matched.

The issue here is that like PEGs `*` quantifier is greedy, It will try to match as much as it can. Thus the last comma in your rule is never reached.
